name: check latest version

on:
  pull_request:
    types:
      - [opened, synchronize]
    branches:
      - main

permissions:
  contents: read

jobs:
  lint-and-fmt:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - uses: actions/checkout@v3

      - name: Check version
        run: scripts/check-version-increase.sh
