name: add tag when pull request is merged

on:
  pull_request:
    types:
      - closed

jobs:
  create_tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - uses: actions/checkout@v3

      - name: Extract Version
        run: echo "version=v$(sh scripts/get-manifest-version.sh)" >> $GITHUB_ENV

      - name: Get Commit URL
        run: echo "commit_url=${{ github.event.pull_request.base.repo.commits_url }}" | sed -e "s#{/sha}#/${{ github.sha }}#" >> $GITHUB_ENV

      - name: Get Commit Message
        run: 'echo "::set-env name=message::$(curl -s -L -H ''Accept: application/vnd.github+json'' ${{ env.commit_url }} | jq ''.commit.message'' | sed -e ''s/\\n/%0A/g'')"'

      - name: Create Tag
        uses: rickstaa/action-create-tag@v1
        id: create-tag
        with:
          tag: ${{ env.version }}
          force_push_tag: true
          tag_exists_error: false
          commit_sha: ${{ github.sha }}
          message: ${{ env.message }}
