name: add tag when pull request is merged

on:
  pull_request:
    types:
      - closed

jobs:
  create_tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: extract-version
        run: echo "version=v$(sh scripts/get-manifest-version.sh)" >> $GITHUB_ENV

      - name: get-commit-url
        run: echo "commit_url=${{ github.event.pull_request.base.repo.commits_url }}" | sed -e "s#{/sha}#/${{ github.sha }}#" >> $GITHUB_ENV

      - name: get-commit-message
        run: 'echo "message=$(curl -s -L -H ''Accept: application/vnd.github+json'' ${{ env.commit_url }} | jq ''.commit.message'')" >> $GITHUB_ENV'

      - name: debug-print
        run: 'echo "version=${{ env.version }}, message=${{ env.message }}"'

    # - uses: rickstaa/action-create-tag@v1
    #     id: "create_tag"
    #     with:
    #       tag: ${{ env.version_in_manifest }}
    #       tag_exists_error: false
    #       message: "Latest release"
